<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Guru_mapel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Guru_mapel_model');
    } 

    /*
     * Listing of guru_mapel
     */
    function index()
    {
        $data['guru_mapel'] = $this->Guru_mapel_model->get_all_guru_mapel();
        
        $data['_view'] = 'guru_mapel/index';
        $this->load->view('template/header',$data);
        $this->load->view('template/sidebar',$data);
        $this->load->view('guru_mapel/index',$data);
        $this->load->view('template/footer',$data);
    }

    /*
     * Adding a new guru_mapel
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('id_guru','Id Guru','required');
		$this->form_validation->set_rules('id_mapel','Id Mapel','required');
		$this->form_validation->set_rules('id_tahun','Id Tahun','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'id_guru' => $this->input->post('id_guru'),
				'id_mapel' => $this->input->post('id_mapel'),
				'id_tahun' => $this->input->post('id_tahun'),
            );
            
            $guru_mapel_id = $this->Guru_mapel_model->add_guru_mapel($params);
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data <strong>'.$params['nama_lengkap'].'</strong>');
            $this->session->set_flashdata('berhasil', 'Anda berhasil menambahkan data guru <strong>'.$params['id_guru'].' mengajar mata pelajaran '.$params['id_mapel'].'</strong>.');
            redirect('guru_mapel/index');
        }
        else
        {
			$this->load->model('Guru_model');
			$data['all_guru'] = $this->Guru_model->get_all_guru();

			$this->load->model('Mapel_model');
			$data['all_mapel'] = $this->Mapel_model->get_all_mapel();

			$this->load->model('Tahun_pelajaran_model');
			$data['all_tahun_pelajaran'] = $this->Tahun_pelajaran_model->get_all_tahun_pelajaran();
            
            $data['_view'] = 'guru_mapel/add';
            $this->load->view('template/header',$data);
            $this->load->view('template/sidebar',$data);
            $this->load->view('guru_mapel/add',$data);
            $this->load->view('template/footer',$data);
        }
    }  

    /*
     * Editing a guru_mapel
     */
    function edit($id)
    {   
        // check if the guru_mapel exists before trying to edit it
        $data['guru_mapel'] = $this->Guru_mapel_model->get_guru_mapel($id);
        
        if(isset($data['guru_mapel']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('id_guru','Id Guru','required');
			$this->form_validation->set_rules('id_mapel','Id Mapel','required');
			$this->form_validation->set_rules('id_tahun','Id Tahun','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'id_guru' => $this->input->post('id_guru'),
					'id_mapel' => $this->input->post('id_mapel'),
					'id_tahun' => $this->input->post('id_tahun'),
                );

                $this->Guru_mapel_model->update_guru_mapel($id,$params);            
                redirect('guru_mapel/index');
            }
            else
            {
				$this->load->model('Guru_model');
				$data['all_guru'] = $this->Guru_model->get_all_guru();

				$this->load->model('Mapel_model');
				$data['all_mapel'] = $this->Mapel_model->get_all_mapel();

				$this->load->model('Tahun_pelajaran_model');
				$data['all_tahun_pelajaran'] = $this->Tahun_pelajaran_model->get_all_tahun_pelajaran();

                $data['_view'] = 'guru_mapel/edit';
                $this->load->view('template/header',$data);
                $this->load->view('template/sidebar',$data);
                $this->load->view('guru_mapel/edit',$data);
                $this->load->view('template/footer',$data);
            }
        }
        else
            show_error('The guru_mapel you are trying to edit does not exist.');
    } 

    /*
     * Deleting guru_mapel
     */
    function remove($id)
    {
        $guru_mapel = $this->Guru_mapel_model->get_guru_mapel($id);

        // check if the guru_mapel exists before trying to delete it
        if(isset($guru_mapel['id']))
        {
            $this->Guru_mapel_model->delete_guru_mapel($id);
            redirect('guru_mapel/index');
        }
        else
            show_error('The guru_mapel you are trying to delete does not exist.');
    }
    
}