/* tabel profil lembaga */
CREATE TABLE profil (
    id int,
    namaSekolah varchar(255),
    npsn varchar(255),
    bentukSekolah varchar(255),
    alamat varchar(255),
    desaKelurahan varchar(255),
    kecamatan varchar(255),
    kabupatenKota varchar(255),
    provinsi varchar(255),
    rt varchar(255),
    rw varchar(255),
    dusun varchar(255),
    kodePos varchar(255),
    lintang varchar(255),
    bujur varchar(255),
    kebutuhahKhususDilayani varchar(255),
    skPendirianSekolah varchar(255),
    tanggalPendirianSekolah varchar(255),
    statusKepemilikan varchar(255),
    yayasan varchar(255),
    skIzinOperasional varchar(255),
    tanggalSkIzinOperasional varchar(255),
    namaYayasan varchar(255),
    alamatYayasan varchar(255),
    rtYayasan varchar(255),
    rwYayasan varchar(255),
    dusunYayasan varchar(255),
    desaKelurahanYayasan varchar(255),
    kecamatanYayasan varchar(255),
    kodePosYayasan varchar(255),
    lintangYayasan varchar(255),
    bujurYayasan varchar(255),
    nomorTeleponYayasan varchar(255),
    nomorFaxYayasan varchar(255),
    emailYayasan varchar(255),
    websiteYayasan varchar(255),
    namaPemimpinYayasan varchar(255),
    nomorPendirianYayasan varchar(255),
    tanggalPendirianYayasan varchar(255),
    nppnBm varchar(255),
    nomorSKBeritaNegara varchar(255),
    tanggalSKBeritaNegara varchar(255)
)

/* tabel siswa */
