<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Guru_mapel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get guru_mapel by id
     */
    function get_guru_mapel($id)
    {
        return $this->db->get_where('guru_mapel',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all guru_mapel
     */
    function get_all_guru_mapel()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('guru_mapel')->result_array();
    }
        
    /*
     * function to add new guru_mapel
     */
    function add_guru_mapel($params)
    {
        $this->db->insert('guru_mapel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update guru_mapel
     */
    function update_guru_mapel($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('guru_mapel',$params);
    }
    
    /*
     * function to delete guru_mapel
     */
    function delete_guru_mapel($id)
    {
        return $this->db->delete('guru_mapel',array('id'=>$id));
    }
}